#!/usr/bin/env python

import sys
import xmlrpclib

exclude_list = ['openstack-lb-service',
                'citrix-geppetto-celeryd',
                'citrix-geppetto-celerycam',
                'openstack-nova-objectstore',
                'openstack-nova-vncproxy',
                '']

master_url = '%s/openstack/geppetto/v1' % sys.argv[1]
vm_tags = sys.argv[2].split(',')
# Purge the list of tags
vm_tags = [ e.strip()[:-1] for e in vm_tags \
                  if e.strip()[:-1] not in exclude_list \
                                    and e.strip() != 'openstack' ]
# Remove duplicates
vm_tags = list(set(vm_tags))

proxy = xmlrpclib.ServerProxy(master_url)
os_roles = proxy.Role.get_service_roles()
# Remove services taht have not been deployed, e.g. lb-service
os_roles = [ e for e in os_roles \
                         if e not in exclude_list ]

os_roles.sort()
vm_tags.sort()

fail=False
for a, b in zip(vm_tags, os_roles):
    if a != b:
        print(a, "is different from", b)
        fail=True

if fail:
  sys.exit(1)

print "All service roles defined have matching tags."
