#!/bin/bash

GIT_TIMEOUT=${GIT_TIMEOUT:-0}
function git_retry {
    local count=0
    local timeout=0

    if [[ -n "${GIT_TIMEOUT}" ]]; then
        timeout=${GIT_TIMEOUT}
    fi

    until timeout -s SIGINT ${timeout} git "$@"; do
        count=$(($count + 1))
        echo "timeout ${count} for git call: [git $@]"
        if [ $count -eq 3 ]; then
            echo "Maximum of 3 git retries reached"
            exit 1
        fi
        sleep 5
    done
}

function repo_lines() {
wget -qO - https://raw.github.com/openstack-dev/devstack/master/stackrc |
    grep -e '=\${[A-Z0-9_]*_REPO:-'
}

function non_git_repos() {
    repo_lines | grep -v GIT_BASE | grep -v "//github.com/"
}

function git_repos() {
    repo_lines | grep -e '\(GIT_BASE\|//github.com/\)'
}

function extract_bash_default() {
    sed -e 's/.*:-\(.*\)}$/\1/g'
}

function extract_var_user_repo() {
    sed -e 's,^.*=\${\(.*\):-.*/\(.*\)/\(.*\)}$,\1 \2 \3,g'
}

function generate_repos() {
    {
        {
            git_repos | extract_var_user_repo
            echo "DEVSTACK_REPO openstack-dev devstack.git"
        } | extract_var_user_repo | sed 's/$/ github/'
        non_git_repos | extract_var_user_repo | sed 's/$/ anongit/'
    } | sort | sed -e '/^BM_IMAGE_BUILD_REPO.*$/d'
}

function assert_no_new_repos() {
diff -u \
    <(generate_repos) \
    - \
    << EOF
CEILOMETERCLIENT_REPO openstack python-ceilometerclient.git github
CEILOMETER_REPO openstack ceilometer.git github
CINDERCLIENT_REPO openstack python-cinderclient.git github
CINDER_REPO openstack cinder.git github
CLIFF_REPO openstack cliff.git github
DEVSTACK_REPO openstack-dev devstack.git github
GLANCECLIENT_REPO openstack python-glanceclient.git github
GLANCE_REPO openstack glance.git github
GLANCE_STORE_REPO openstack glance_store.git github
HEAT_CFNTOOLS_REPO openstack heat-cfntools.git github
HEATCLIENT_REPO openstack python-heatclient.git github
HEAT_REPO openstack heat.git github
HEAT_TEMPLATES_REPO openstack heat-templates.git github
HORIZONAUTH_REPO openstack django_openstack_auth.git github
HORIZON_REPO openstack horizon.git github
IRONICCLIENT_REPO openstack python-ironicclient.git github
IRONIC_PYTHON_AGENT_REPO openstack ironic-python-agent.git github
IRONIC_REPO openstack ironic.git github
KEYSTONECLIENT_REPO openstack python-keystoneclient.git github
KEYSTONEMIDDLEWARE_REPO openstack keystonemiddleware.git github
KEYSTONE_REPO openstack keystone.git github
NEUTRONCLIENT_REPO openstack python-neutronclient.git github
NEUTRON_REPO openstack neutron.git github
NOVACLIENT_REPO openstack python-novaclient.git github
NOVA_REPO openstack nova.git github
NOVNC_REPO kanaka noVNC.git github
OAC_REPO openstack os-apply-config.git github
OCC_REPO openstack os-collect-config.git github
OPENSTACKCLIENT_REPO openstack python-openstackclient.git github
ORC_REPO openstack os-refresh-config.git github
OSLOCFG_REPO openstack oslo.config.git github
OSLOCON_REPO openstack oslo.concurrency.git github
OSLODB_REPO openstack oslo.db.git github
OSLOI18N_REPO openstack oslo.i18n.git github
OSLOLOG_REPO openstack oslo.log.git github
OSLOMID_REPO openstack oslo.middleware.git github
OSLOMSG_REPO openstack oslo.messaging.git github
OSLORWRAP_REPO openstack oslo.rootwrap.git github
OSLOSERIALIZATION_REPO openstack oslo.serialization.git github
OSLOUTILS_REPO openstack oslo.utils.git github
OSLOVMWARE_REPO openstack oslo.vmware.git github
PBR_REPO openstack-dev pbr.git github
PECAN_REPO stackforge pecan.git github
PYCADF_REPO openstack pycadf.git github
REQUIREMENTS_REPO openstack requirements.git github
RYU_REPO osrg ryu.git github
SPICE_REPO spice spice-html5.git anongit
SQLALCHEMY_MIGRATE_REPO stackforge sqlalchemy-migrate.git github
STEVEDORE_REPO openstack stevedore.git github
SWIFT3_REPO stackforge swift3.git github
SWIFTCLIENT_REPO openstack python-swiftclient.git github
SWIFT_REPO openstack swift.git github
TASKFLOW_REPO openstack taskflow.git github
TEMPEST_LIB_REPO openstack tempest-lib.git github
TEMPEST_REPO openstack tempest.git github
TIE_REPO openstack tripleo-image-elements.git github
TROVECLIENT_REPO openstack python-troveclient.git github
TROVE_REPO openstack trove.git github
WSME_REPO stackforge wsme.git github
EOF
}

function dst_repo() {
    local repo

    repo="$1"

    local reponame

    reponame=$(echo "$repo" | cut -d" " -f 3)

    echo "git://gold.eng.hq.xensource.com/git/internal/builds/$reponame"
}

function public_repo() {
    local repo

    repo="$1"

    local reponame

    reponame=$(echo "$repo" | cut -d" " -f 3)

    echo "git@github.com:citrix-openstack-build/$reponame"
}

function source_repo() {
    local repo

    repo="$1"

    local varname
    local username
    local reponame
    local provider

    varname=$(echo "$repo" | cut -d" " -f 1)
    username=$(echo "$repo" | cut -d" " -f 2)
    reponame=$(echo "$repo" | cut -d" " -f 3)
    provider=$(echo "$repo" | cut -d" " -f 4)

    echo "git://gold.eng.hq.xensource.com/git/$provider/$username/$reponame"
}

function var_name() {
    local repo

    repo="$1"

    local varname

    varname=$(echo "$repo" | cut -d" " -f 1)

    echo "$varname"
}

function branch_name() {
    local repo

    repo="$1"

    local varname

    varname=$(var_name "$repo")

    echo "$varname" | sed -e 's/_REPO/_BRANCH/g'
}

function repo_name() {
    local repo

    repo="$1"

    local reponame

    reponame=$(echo "$repo" | cut -d" " -f 3)

    echo "$reponame"
}

function init_non_existing_repos() {
    local repo
    local varname

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        [ -d "$varname" ] || git init "$varname"
    done
}

function add_build_remote() {
    local repo
    local varname

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        (
            cd "$varname"
            if ! git remote -v | grep -q "^build"; then
                git remote add build $(dst_repo "$repo")
            fi
        )
    done
}

function add_public_remote() {
    local repo
    local varname

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        (
            cd "$varname"
            if git remote -v | grep -q "^public"; then
                echo "Removed public remote"
                git remote rm public
            fi
            echo "Add public remote"
            git remote add public $(public_repo "$repo")
        )
    done
}

function add_origin_remote() {
    local repo
    local varname

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        (
            cd "$varname"
            if ! git remote -v | grep -q "^origin"; then
                git remote add origin $(source_repo "$repo")
            fi
        )
    done
}

function with_all_repos() {
    local args
    local repo
    local varname

    args="$@"

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        (
            cd "$varname"
            $@
        )
    done
}

function reset_repos() {
    local args
    local repo
    local varname

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        (
            cd "$varname"
            git reset --hard || true > /dev/null 2>&1
        )
    done
}

function create_local_build_branch() {
    local branch
    local repo
    local varname

    branch="$1"

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        [ -d "$varname" ] || git_retry clone $(source_repo "$repo") "$varname"
        (
            set -e
            cd "$varname"

            git_retry fetch -q origin || true # Ignore fetch errors
            git_retry checkout --quiet origin/master -B "$branch"
            if ! git remote -v | grep -q "^build"; then
                git remote add build $(dst_repo "$repo")
            fi
        )
    done
}

function print_updated_repos() {
    local branch1
    local branch2

    branch1="$1"
    branch2="$2"

    local reponame
    local varname

    generate_repos | while read repo; do
        varname=$(var_name "$repo")
        reponame=$(repo_name "$repo")

        cd "$varname"
        if ! git diff --quiet "$branch1" "$branch2"; then
            echo "$reponame"
        fi
        cd ..
    done
}

function clone_status_repo() {
    local srcrepo
    local ldir

    srcrepo="$1"
    ldir="$2"


if ! [ -d "$ldir" ]; then
    git_retry clone "$srcrepo" "$ldir"
fi
}

function pull_status_repo() {
    local ldir

    ldir="$1"

    (
        cd "$ldir"
        git_retry pull
    )
}

function write_latest_branch() {
    local ldir

    ldir="$1"

    cat > "$ldir/latest_branch"
}

function read_latest_branch() {
    local ldir

    ldir="$1"

    cat "$ldir/latest_branch"
}

function push_status_repo() {
    local ldir

    ldir="$1"

    (
        cd "$ldir"
        git commit -am "Automatic update"
        git_retry push
    )
}
