#!/usr/bin/env python

import sys
import time
import pprint
import xmlrpclib

SUCCESS = "SUCCESS"
RETRIES = "RETRY"

master_url = '%s/openstack/geppetto/v1' % sys.argv[1]

proxy = xmlrpclib.ServerProxy(master_url)

print 'Checking that all the tasks have completed correctly...'

for x in xrange(1,5):
    task_details = proxy.Task.get_details(proxy.Task.get_all())
    errors = len(task_details)
    retries = 0
    for task_uuid, details in task_details.iteritems():
        if details['status'] == SUCCESS:
            errors = errors - 1
        if details['status'] == RETRIES:
            print 'Task %s is set to retry..' % task_uuid
            retries = retries + 1
    if retries > 0:
        print 'Some tasks are yet to complete, waiting...'
        time.sleep(60)

if errors > 0:
    print 'Found some problems, full details below:'
    print pprint.pformat(task_details, 2)
    sys.exit(1)

print 'Passed'
sys.exit(0)
