#!/usr/bin/env python

import sys
import xmlrpclib

master_url = '%s/openstack/geppetto/v1' % sys.argv[1]

proxy = xmlrpclib.ServerProxy(master_url)
fqdns = proxy.Node.get_all()


hostnames=[ n.split('.')[0] for n in fqdns]

for hostname in hostnames:
    print hostname,