#!/usr/bin/env python

import sys
import xmlrpclib

master_url = '%s/openstack/geppetto/v1' % sys.argv[1]
role = sys.argv[2]
prop = None
if len(sys.argv) == 4:
    prop = sys.argv[3]
if len(sys.argv) == 5:
    node_idx = sys.argv[4]
else:
    node_idx = 0

proxy = xmlrpclib.ServerProxy(master_url)

nodes = proxy.Node.get_by_role(role)

if node_idx >= len(nodes):
    print >> sys.stderr, ("The requested node with role %(role)s cannot be found. "
                         "nodes = %(nodes)s") % locals()
    sys.exit(1)

node = nodes[node_idx]
if prop:
    details = proxy.Node.get_details([node])
    if prop in details[node]:
        if details[node][prop] != 'N/A':
            print details[node][prop]
            sys.exit(0)
        else:
            print >> sys.stderr, ('The property %s has not been reported on '
                                  'node %s. Bailing!') % (prop, node)
            sys.exit(1)

print node
