#!/bin/bash
set -eux

LOCK=$1

virtualenv .env
set +u
. .env/bin/activate
set -u

pip install requests
pip install -I http://core.xenrt.citrite.net/xenrtapi.tar.gz

machine_entry=`xenrt mlist -s SJCLAB01 -o OPENSTACK -m | grep "LOCK=$LOCK" | cat`
if [ -n "$machine_entry" ]; then
    machine_name=${machine_entry%% *}
    xenrt return $machine_name
else
    echo "No such lock ($LOCK)"
    exit 1
fi

