#!/usr/bin/env python

import database
import argparse
import sys

parser = argparse.ArgumentParser(description='Get all details of a single server')
parser.add_argument('host', help='host name')
args = parser.parse_args()


for host_entry in database.get_database('server.database'):
    if host_entry.get('HOST') == args.host:
        for item in host_entry.items():
            print '%s=%s' % item
        sys.exit(0)

sys.exit(1)
