#!/bin/bash
set -eux

FUNC_DIR=$(cd $(dirname "${BASH_SOURCE:-$0}") && pwd)
source ${FUNC_DIR}/functions

# redirect stdout to stderr

LOCK=$1

setup_env >&2

machine_entry=`xenrt mlist -s SJCLAB01 -o OPENSTACK -m | grep "LOCK=$LOCK" | cat`
if [ -n "$machine_entry" ]; then
    machine_name=${machine_entry%% *}
    xenrt return $machine_name
else
    echo "No such lock ($LOCK)" >&2
    exit 1
fi

