#!/bin/bash
set -eu

FUNC_DIR=$(cd $(dirname "${BASH_SOURCE:-$0}") && pwd)
source ${FUNC_DIR}/functions

REASON=${1:-""}
if [ "$REASON" == "--reason" ]; then
shift
REASON=${1:-""}
fi

LOCK=`head -c100 /dev/urandom | tr -dc A-Za-z0-9 | head -c 8`

# Redirect stdout for these commands
setup_env >&2

machine_entry=`xenrt mlist -s SJCLAB01 -o OPENSTACK -R "memory>12G/disk1>=120G" -n | tail -n+3 | shuf -n1`
machine_name=${machine_entry%% *}
xenrt borrow $machine_name -f -r "(LOCK=$LOCK) $REASON"

echo "HOST=${machine_name}.xenrt.xs.citrite.net"
echo "LOCK=$LOCK"
