#!/usr/bin/env python

from getters import wait_for_first


def is_pdu(item):
    try:
        return (
            "PDU" == item.get("TYPE")
            and "13" == item.get("RACK")
        )
    except:
        return False


pdu_data, lock = wait_for_first(is_pdu)

for item in pdu_data.items():
    print '%s=%s' % item

print "LOCK=%s" % lock
