#!/usr/bin/env python

from getters import wait_for
from selectors import first_pair_where_vlans_match


items, lock = wait_for(first_pair_where_vlans_match)

for idx, server in enumerate(items):
    for key, value in server.items():
        print "%s%s=%s" % (key, idx, value)

print "LOCK=%s" % lock
