#!/usr/bin/env python

from getters import wait_for_first
import sys


host, = sys.argv[1:]

def is_required_server(item):
    try:
        return host == item.get("HOST")
    except:
        return False


server_data, lock = wait_for_first(is_required_server)

for item in server_data.items():
    print '%s=%s' % item

print "LOCK=%s" % lock
