#!/bin/bash
set -eux

# redirect stdout to stderr

LOCK=$1

exec 3>&1
exec 1>&2

[ -e .env ] || virtualenv .env
set +u
. .env/bin/activate
set -u

if [ ! -e `which xenrt` ]; then
  pip install requests
  pip install -I http://core.xenrt.citrite.net/xenrtapi.tar.gz
fi

exec 1>&3
exec 3>&-

machine_entry=`xenrt mlist -s SJCLAB01 -o OPENSTACK -m | grep "LOCK=$LOCK" | cat`
if [ -n "$machine_entry" ]; then
    machine_name=${machine_entry%% *}
    xenrt return $machine_name
else
    echo "No such lock ($LOCK)" >&2
    exit 1
fi

